/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/approval-pending`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/kyc`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-selection`; params?: Router.UnknownInputParams; } | { pathname: `/verify-company`; params?: Router.UnknownInputParams; } | { pathname: `/verify-government`; params?: Router.UnknownInputParams; } | { pathname: `/verify-institution`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/employer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/government`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/institution`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/youth`; params?: Router.UnknownInputParams; } | { pathname: `/signup/employer`; params?: Router.UnknownInputParams; } | { pathname: `/signup/government`; params?: Router.UnknownInputParams; } | { pathname: `/signup/institution`; params?: Router.UnknownInputParams; } | { pathname: `/signup/youth`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/approval-pending`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/kyc`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-company`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-government`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-institution`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/employer`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/government`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/institution`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard/youth`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/employer`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/government`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/institution`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/youth`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/approval-pending${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/kyc${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile-selection${`?${string}` | `#${string}` | ''}` | `/verify-company${`?${string}` | `#${string}` | ''}` | `/verify-government${`?${string}` | `#${string}` | ''}` | `/verify-institution${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/dashboard/employer${`?${string}` | `#${string}` | ''}` | `/dashboard/government${`?${string}` | `#${string}` | ''}` | `/dashboard/institution${`?${string}` | `#${string}` | ''}` | `/dashboard/youth${`?${string}` | `#${string}` | ''}` | `/signup/employer${`?${string}` | `#${string}` | ''}` | `/signup/government${`?${string}` | `#${string}` | ''}` | `/signup/institution${`?${string}` | `#${string}` | ''}` | `/signup/youth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/approval-pending`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/kyc`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile-selection`; params?: Router.UnknownInputParams; } | { pathname: `/verify-company`; params?: Router.UnknownInputParams; } | { pathname: `/verify-government`; params?: Router.UnknownInputParams; } | { pathname: `/verify-institution`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/employer`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/government`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/institution`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard/youth`; params?: Router.UnknownInputParams; } | { pathname: `/signup/employer`; params?: Router.UnknownInputParams; } | { pathname: `/signup/government`; params?: Router.UnknownInputParams; } | { pathname: `/signup/institution`; params?: Router.UnknownInputParams; } | { pathname: `/signup/youth`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
